sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rneezar2/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rneezar2/react-test npm test

after_success:
  - docker build -t rneezar2/reddit-client ./client
  - docker build -t rneezar2/reddit-nginx ./nginx
  - docker build -t rneezar2/reddit-server ./server

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rneezar2/reddit-client
  - docker push rneezar2/reddit-nginx
  - docker push rneezar2/reddit-server
