sudo: required
language: generic

services:
  - docker

script:
  - docker build -t rneezar2/reddit-client --build-arg NEXT_PUBLIC_SERVER_BASE_URL="$NEXT_PUBLIC_SERVER_BASE_URL" --build-arg NEXT_PUBLIC_CLIENT_BASE_URL="$NEXT_PUBLIC_CLIENT_BASE_URL" --build-arg APP_DOMAIN="$APP_DOMAIN" ./client
  - docker build -t rneezar2/reddit-nginx ./nginx
  - docker build -t rneezar2/reddit-server ./server

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rneezar2/reddit-client
  - docker push rneezar2/reddit-nginx
  - docker push rneezar2/reddit-server
