sudo: required
language: generic

services:
  - docker

after_success:
  - docker build -t rneezar2/reddit-client ./client
  - docker build -t rneezar2/reddit-nginx ./nginx
  - docker build -t rneezar2/multi-server ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rneezar2/reddit-client
  - docker push rneezar2/reddit-nginx
  - docker push rneezar2/reddit-server
